name: PHP Composer

on:
  push:
    tags:
      - 'release-**' 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.4'
          tools: composer, box
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Compile PHAR
      run: box compile -n
    
    - name: Create Release
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: bin/phantasia.phar